apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : api-gate
  namespace: xarv-ns
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : in-cluster
    namespace: api-gate
  source:
    path   : "manifests/api-gate/development"
    repoURL: "git@github.com:shkiperko0/k8s-manifests.git"
    targetRevision: HEAD
    # helm:
    #   valueFiles:
    #   - values_dev.yaml
    #   parameters:
    #   - name: "container.image"
    #     value: adv4000/app1:v3

  project: xarv-dev
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true    

