apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : root
  namespace: xarv-ns
spec:
  destination:
    name     : in-cluster
    namespace: argocd
  source:
    path   : "manifests/development/applications"
    repoURL: "git@github.com:shkiperko0/k8s-manifests.git"
    targetRevision: HEAD
  project: xarv-dev
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
      